import govLogo from '../assets/images/brand/gov-bermuda-logo.jpg'

const base = import.meta.env.BASE_URL || '/';

export const BRANDING = {
  logo: govLogo,
  logoPublic: base + 'gov-bermuda-logo.jpg',
  logoAlt: 'Government of Bermuda — Department of Energy',
  departmentName: 'Department of Energy',
  governmentName: 'Government of Bermuda',
  domain: 'energy.bm',
  phone: '+1 (441) 444-0597',
  colors: {
    govBlue: '#2E5496',
    navy: '#0B1F3A',
    teal: '#0077B6',
    gold: '#C9A227',
  },
}

/** Local images in /public/images — each mapped to a relevant subject */
export const PAGE_IMAGES = {
  energy: base + 'images/energy.jpg',
  solar: base + 'images/solar.jpg',
  solarRooftop: base + 'images/solar-rooftop.jpg',
  solarCommercial: base + 'images/solar-commercial.jpg',
  bermuda: base + 'images/bermuda.jpg',
  bermudaVision: base + 'images/bermuda-vision.webp',
  government: base + 'images/government.jpg',
  space: base + 'images/space.jpg',
  education: base + 'images/education.jpg',
  ev: base + 'images/ev.jpg',
  consultation: base + 'images/consultation.jpg',
  home: base + 'images/home.jpg',
  simulator: base + 'images/home.jpg',
  battery: base + 'images/battery-storage.jpg',
  van: base + 'images/van.jpg',
  bus: base + 'images/bus.jpg',
  motorcycle: base + 'images/motorcycle.jpg',
  grid: base + 'images/grid.jpg',
  wind: base + 'images/wind.jpg',
  innovation: base + 'images/innovation.jpg',
  bursary: base + 'images/bursary.jpg',
  registry: base + 'images/registry.jpg',
  efficiency: base + 'images/efficiency.jpg',
  analytics: base + 'images/analytics.jpg',
  blockchain: base + 'images/blockchain.jpg',
  telecom: base + 'images/telecom.jpg',
  charging: base + 'images/charging.jpg',
  transport: base + 'images/transport.jpg',
  contact: base + 'images/bermuda.jpg',
  policy: base + 'images/consultation.jpg',
  spaceOrbit: base + 'images/space-orbit.jpg',
  spaceEarth: base + 'images/space-earth.jpg',
  spaceDish: base + 'images/space-dish.jpg',
  spaceLaunch: base + 'images/space-launch.jpg',
  spaceInsurance: base + 'images/space-insurance.jpg',
  spaceStrategy: base + 'images/space-strategy.jpg',
  spaceAstronaut: base + 'images/space-astronaut.jpg',
  spaceNightsky: base + 'images/space-nightsky.jpg',
  hamiltonStreet: base + 'images/hamilton-street.jpg',
  educationOutreach: base + 'images/education-outreach.jpg',
  electricBus: base + 'images/electric-bus.jpg',
  electricBuses: base + 'images/electric-buses.jpg',
  gisHeatmap: base + 'images/gis-heatmap.jpg',
  satellite: base + 'images/satellite.jpg',
  spaceSatellites: base + 'images/space-satellites.jpg',
  solarFieldBermuda: base + 'images/solar-field-bermuda.jpg',
  batteryStorage: base + 'images/battery-storage.jpg',
  dockyardSolar: base + 'images/dockyard-solar.jpg',
  govSolarField: base + 'images/gov-solar-field.jpg',
  bhcHousing: base + 'images/bhc-housing.jpg',
  balconySolar: base + 'images/balcony-solar.jpg',
  floatingSolar: base + 'images/floating-solar.jpg',
  solarWorkers: base + 'images/solar-workers.jpg',
  windTurbine: base + 'images/wind-turbine.jpg',
  evExpo: base + 'images/ev-expo.jpg',
  portrait: base + 'images/portrait.jpg',
  portrait1: base + 'images/portraits/774909.jpg',
  portrait2: base + 'images/portraits/91227.jpg',
  portrait3: base + 'images/portraits/1181519.jpg',
  portrait4: base + 'images/portraits/1181686.jpg',
  portrait5: base + 'images/portraits/1222271.jpg',
  portrait6: base + 'images/portraits/2379004.jpg',
}

export const IMAGE_FALLBACK = PAGE_IMAGES.solar
