export const ROUTES = {
  home: '/',
  about: '/about',
  energy: '/energy',
  installers: '/energy/installers',
  vehicles: '/energy/vehicles',
  electronicCommunications: '/electronic-communications',
  broadcasting: '/broadcasting',
  spaceSatellite: '/space-satellite',
  policies: '/policies',
  consultations: '/consultations',
  progressTracker: '/progress-tracker',
  projects: '/projects',
  projectDetail: (id) => `/projects/${id}`,
  dashboard: '/dashboard',
  // The Renewable Dashboard and the Renewable Energy Registry are one page.
  // The two paths below are kept so existing links and bookmarks still land
  // somewhere: both redirect here.
  renewableResource: '/renewable-energy-resource',
  renewableDashboard: '/dashboard/renewable',
  transitionDashboard: '/dashboard/transition',
  registry: '/registry',
  gis: '/gis',
  education: '/education',
  bursary: '/bursary',
  simulator: '/simulator',
  innovation: '/innovation',
  news: '/news',
  newsArticle: (slug) => `/news/${slug}`,
  contact: '/contact',
  privacy: '/privacy',
  terms: '/terms',
  accessibility: '/accessibility',
  cookies: '/cookies',
  imageCredits: '/image-credits',
}
